### ISSUE TITLE
CSS compilation error

### ISSUE THREAD

**Issue by afhbl** [tolk/tolk#105]
`V8::Error: /var/bundle/ruby/2.1.0/gems/tolk-1.9.1/app/assets/stylesheets/tolk/application.css:1:1: Unknown word`

rails 4.2.1
sprockets 3.0.1
autoprefixer-rails 5.1.11

Looks like application.css should looks like
```css
//= require 'tolk/reset.css'
//= require 'tolk/screen.css'
```
instead of
```css
# =require 'tolk/reset.css'
# =require 'tolk/screen.css'
```

**Comment by thomasdarde** [comment]
This is on master
