### ISSUE TITLE
dump makes problem

### ISSUE THREAD

**Issue by meysammeisam** [tolk/tolk#107]
on Apply Changes or use any rake ***tolk:dump**** ,the specific files update but you will see : 
 
***Routing Error
uninitialized constant Tolk::Pagination***

and should restart the server(rails s).

**Comment by thomasdarde** [comment]
New version of tolk is agnostic from a specific pagination gem. You need to include kaminari or will_paginate

**Comment by meysammeisam** [comment]
we use kaminari and TOLK works very well until we dump the translated phrases into files!

**Comment by nicolasgarnil** [comment]
+1 
Same issue after running `tolk:sync`. I fixed it restarting the server.

**Comment by thiyagarajan** [comment]
+1

We are also getting same error. Every time we are restarting server while save changes.

**Comment by thomasdarde** [comment]
have you tried version  1.9.1

-

 <https://sigilium.com/signatures/rcDC_ix8fTp6sz8EERs4GCcz41fX0rc/link>

**Comment by fake-or-dead** [comment]
+1 

I use tolk 1.9.1 with kaminari and happened with me too

**Comment by wpp** [comment]
Ran into this a couple of times today. Restarting the server "fixed" it for me as well.

**Comment by arashm** [comment]
I have this problem with Kaminari and Tolk 1.9.2. Constantly getting `uninitialized constant Tolk::Pagination` which is very annoying.

**Comment by wpp** [comment]
I've fixed my Issue with the changes in #111 for now. If some of you would like to try it out and see if it solves your problems as well, you could simply add:

    gem 'tolk', github: 'wpp/tolk', branch: 'pagination_constant'

to your Gemfile for now.

**Comment by thomasdarde** [comment]
Thank @wpp merged and released.
