### ISSUE TITLE
NoMethodError: undefined method `paginates_per'  withoud Kaminari (v1.8.0)

### ISSUE THREAD

**Issue by nicolasgarnil** [tolk/tolk#108]
I have `will_paginate` installed but I still need to install `kaminari` in order to not receive the "undefined method paginates_per" error.

```bash
$ bundle exec rake tolk:sync
rake aborted!
NoMethodError: undefined method `paginates_per' for #<Class:0x007fbf7604b5e0>
```

Tolk Version: 1.8.0
Ruby: 2.2.1

Also tried with 1.9.0.

**Comment by lime** [comment]
What version of `will_paginate` are you using?

**Comment by lime** [comment]
Nevermind, I can reproduce with `tolk` 1.9.1 and `will_paginate` 3.0.7.

Looks like [`config/initializers/will_paginate.rb`](https://github.com/tolk/tolk/blob/master/config/initializers/will_paginate.rb) doesn't initialize properly, despite working in the tests. Odd.

**Comment by lime** [comment]
Duh, the initializer was never included in the built gem... Fix incoming.

**Comment by simicic** [comment]
I am experience an issue with tolk while running it with RAILS_ENV=production
- Rails 4.2.5.1
- Ruby 2.3.0
- Kaminari 0.16.3 and/or will_paginate 3.1.0
- Tolk 1.9.3 (I also tried 1.9.2 and 1.9.1, the attempt to use 1.8.1 failed with an error in assets precompilation)

The issue does not happen when using development environment (assuming most of default setting  properties).

I tried: 
- all combination of including will_paginate and/or kaminari and tolk 
- including will_paginate initializer as part of my initializers 
(didn't work)

Commenting out tolk itself enables me to call for  ex: Tolk:Phrase. paginates_per(10) but of course. I do not have the entire engine. 

There might be something wrong with the dependencies?
Does anyone experience this issue? Do you have a hint what could I check further to resolve this one?

Thanks!

**Comment by dnrce** [comment]
@simicic, can you please file this in a new ticket and include specific error output? Thanks.
