### ISSUE TITLE
I can login with wrong username and password

### ISSUE THREAD

**Issue by davidslvto** [tolk/tolk#11]
Hi guys, 

I'm using Tolk for the first time, and followed the authentication example.

And then I wrote a wrong username and password and I logged in successfuly.

This is my tolk.rb initializer

``` ruby
# encoding: utf-8

# Tolk config file. Generated on June 29, 2012 15:26
# See github.com/tolk/tolk for more informations


Tolk::ApplicationController.authenticator = proc {
  authenticate_or_request_with_http_basic do |user_name, password|
    user_name == 'translator' && password == 'transpass'
  end
}

Tolk::Locale.primary_locale_name = :pt

Tolk.config do |config|

  # If you need to add a mapping do it like this :
  # May we suggest you use http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
  # config.mapping["fr-ES"] = 'Frañol !'

end
```

Thanks

**Comment by julianlecalvez** [comment]
Hi, 

It seems that the proc is not executed each time. 
In my case, I tried in development mode and the proc is executed only the first time after the server started. Then the second time I reload the page, the interface is accessible (even if it wasn't the first time). 
So I tried to deploy in my preproduction mode, but in this case, it doesn't even execute my proc (not even one time). 

Thank you for your help :) 

Julian
