### ISSUE TITLE
Avoiding text strip of translations

### ISSUE THREAD

**Issue by fernandomm** [tolk/tolk#114]
Is there a reason why it isn't possible to avoid translation's text strip?

https://github.com/tolk/tolk/blob/7a854f4ba45a093f45ef244fdf568813657c42b9/app/models/tolk/translation.rb#L62

Depending on the language that you're using, Rails translations like support.array.two_words_connector ( " and " ) need spaces at the beginning and at the end of the string. It isn't possible to use Tolk to set it.

**Comment by thomasdarde** [comment]
Hi @fernandomm 
No reason aside it's better in the vast majority of case.
A PR making this optional would be happily merged !
