### ISSUE TITLE
NoMethodError: undefined method `paginates_per' 

### ISSUE THREAD

**Issue by simicic** [tolk/tolk#123]
I am experience an issue with tolk while running it with RAILS_ENV=production

- Rails 4.2.5.1
- Ruby 2.3.0
- Kaminari 0.16.3 and/or will_paginate 3.1.0
- Tolk 1.9.3 (I also tried 1.9.2 and 1.9.1, the attempt to use 1.8.1 failed with an error in assets precompilation)

The issue does not happen when using development environment (assuming most of default setting properties).

I tried:

- all combination of including will_paginate and/or kaminari and tolk
- including will_paginate initializer as part of my initializers (didn't work)

Commenting out tolk itself enables me to call for ex: Tolk:Phrase. paginates_per(10) but of course. I do not have the entire engine.

Complete output you can find here: 
https://gist.github.com/simicic/55b995e25e03aa165a5c

There might be something wrong with the dependencies?
Does anyone experience this issue? Do you have a hint what could I check further to resolve this one?

Thanks!

**Comment by simicic** [comment]
Hm, after long debugging issue has been found. 
Rails env was set to production while the app at this stage expected acceptance. (Part is overriden on the server by the third party we use, I have not seen it earlier)

I guess this can be closed since it is not a real one! Still, hope it helps someone...

**Comment by dnrce** [comment]
Glad to hear you figured it out. Thanks for following up and letting us know the resolution!
