### ISSUE TITLE
Latest version of tolk not on rubygems

### ISSUE THREAD

**Issue by NomNomCameron** [tolk/tolk#124]
Getting this when trying to bundle:

```
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.0.0)

  In Gemfile:
    rails

    rails

    tolk (~> 1.9.3) was resolved to 1.9.3, which depends on
      rails (< 4.3, >= 4.0)
```

Last update on rubygems shows May 15 2015, this doesn't reflect the changes to support rails 5 as a dependency that's on this repo

**Comment by pashazel** [comment]
+ same problem

**Comment by PhilippeBo** [comment]
Same for **rails 5.0.0.1**
```
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.0.0.1)

  In Gemfile:
    rails (~> 5.0.0.1)

    tolk (= 1.9.3) was resolved to 1.9.3, which depends on
      rails (< 4.3, >= 4.0)
```

Is there going to be a little update soon ?

**Comment by NomNomCameron** [comment]
@PhilippeBo if you need to use this in the meantime while the maintainer gets the newest version on rubygems you can use this forked version:
https://github.com/NomNomCameron/tolk

**Comment by thomasdarde** [comment]
Hi, I've just release 2.0.0.
Can you confirm me it's all-right now ?
