### ISSUE TITLE
Incorrect Serbia country code

### ISSUE THREAD

**Issue by atothewest** [tolk/tolk#132]
Have noticed that the specified country code in Tolk for Serbia is incorrectly set to "SR", when Serbia's official ISO country code is in fact "RS": 

https://en.wikipedia.org/wiki/Serbia

Noticed this working on an internationalisation project recently, when the national flag of Suriname (whose ISO code is "SR") was incorrectly loaded in for a Serbian locale.

**Comment by thomasdarde** [comment]
Hi Atothewest

We are using language iso-code, not country iso-code :

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
