### ISSUE TITLE
Documentation of `block_xxx_en_yml_locale_files`

### ISSUE THREAD

**Issue by ekampp** [tolk/tolk#145]
The https://github.com/tolk/tolk#settings section of the readme states that `block_xxx_en_yml_locale_files` will exclude `xxx.en.yml` files. I believe the real behavior is that it, in fact, excludes `xxx.<locale>.yml` files. 

Perhaps this can be clarified?

**Comment by thomasdarde** [comment]
fixed in last pr

**Comment by ekampp** [comment]
Thanks 🎉
