### ISSUE TITLE
Support for Rails 6.0

### ISSUE THREAD

**Issue by AhmedKamal20** [tolk/tolk#152]
Is there a plan to support Rails 6?

**Comment by thomasdarde** [comment]
No plan, but definitely happy to accept a PR !

**Comment by Migoo** [comment]
hello @thomasdarde,

I just made one :) 

https://github.com/tolk/tolk/pull/154

Thanks for watching

**Comment by niciliketo** [comment]
I can see tests are failing  - would this get merged if tests are fixed?

**Comment by thomasdarde** [comment]
Test are passing on this one, it's on master !

**Comment by niciliketo** [comment]
Thank you @thomasdarde
