### ISSUE TITLE
Clean Rails 3.2.7 Install - New locale has 106 translations required 

### ISSUE THREAD

**Issue by timhaines** [tolk/tolk#18]
I created a brand new rails project, and added tolk and nothing else.

Creating a new locale says there are 106 translations required.  It would be great if these could be reduced or eliminated to save translators time.

I first noticed that tolk was adding will_paginate translations required, when tolk is the only reason will_paginate is included.  It would be nice for these not to be included if will_paginate isn't used anywhere else.

The other items that are created are likely from standard rails items.  Perhaps they could be automatically seeded from a localization project such as http://github.com/svenfuchs/rails-i18n/tree/master/rails%2Flocale

**Comment by thomasdarde** [comment]
An option now allows to only import certain files from the locales
